Move amm functions to library #20
yieldyak/smart-contracts pull request #27
Opened 2021-08-05 17:32 UTC by midnight-commit

Compiles and should be fine but untested

Added:
DexLibrary
JoeStrategyV3
DexStrategyV6

2021-08-05 21:23 UTC, ASlowCheetah requested changes
One last review before we're ready to merge :D

2021-08-05 21:23 UTC, ASlowCheetah commented on contracts/lib/DexLibrary.sol
> +    function convertWAVAXToDepositTokens(uint amount, address depositToken, IPair swapPairToken0, IPair swapPairToken1) internal returns (uint, uint) {
Check `_convertRewardTokensToDepositTokens` from the DexV6, this function could be generalized like that one just passing an extra argument "ERC20 rewardToken"

2021-08-05 21:23 UTC, ASlowCheetah commented on contracts/strategies/DexStrategyV6.sol
> +    function _convertRewardTokensToDepositTokens(uint amount) private returns (uint) {
then we would be able to remove this function

2021-08-05 21:23 UTC, ASlowCheetah commented on contracts/strategies/DexStrategyV6.sol
> +        uint depositTokenAmount = _convertRewardTokensToDepositTokens(
and call the library here

2021-08-05 21:23 UTC, ASlowCheetah commented on contracts/strategies/JoeStrategyV3.sol
> +        (uint amountOutToken0, uint amountOutToken1) = DexLibrary.convertWAVAXToDepositTokens(
And here would work too, we would just need to make sure we pass the argument rewardToken as the WAVAX defined in the contract

2021-08-06 18:34 UTC, midnight-commit commented
Very good suggestions, @ASlowCheetah, thank you! Not sure why I missed those.

One thing I noticed is that "convertRewardTokensToDepositTokens" actually does more than it says by also adding the liquidity at the end. This kind of bothers me. I think we should change the name to something like "addRewardToLiquidity" or remove "addLiquidity" from "convertRewardTokensToDepositTokens" and make it a separate call in the strategies.
What do you think?

2021-08-06 18:39 UTC, ASlowCheetah commented
I I think this function is ok, the name says it all, it's supposed to take the reward token(any), and convert that to the deposit token(which is a liquidity token), the underlying means in which it does that is just technical details, but I do agree that it is currently doing way more than it should in one block of code, nothing to worry about right now

2021-08-10 19:18 UTC, merged